# Generated by Django 5.0.2 on 2024-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
