# Generated by Django 4.2.10 on 2024-03-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_rename_acceptancetests_acceptancetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='acceptance_tests',
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='userStroy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrum.userstory'),
            preserve_default=False,
        ),
    ]
