# Generated by Django 5.0.2 on 2024-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_user_admin_user_user_mail_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
