# Generated by Django 4.2.10 on 2024-03-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_remove_userstory_acceptance_tests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptancetest',
            old_name='userStroy',
            new_name='user_stroy',
        ),
    ]
