# Generated by Django 4.2.10 on 2024-03-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_rename_userstroy_acceptancetest_user_stroy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancetest',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
