# Generated by Django 4.2.10 on 2024-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_alter_acceptancetest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='acceptance_tests',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AcceptanceTest',
        ),
    ]
