# Generated by Django 5.0.2 on 2024-02-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0006_assignedrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
