# Generated by Django 5.0.2 on 2024-03-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0008_alter_user_password_alter_user_username'),
        ('scrum', '0008_default_user'),
    ]

    operations = [
    ]
