# Generated by Django 5.0.2 on 2024-03-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='duration',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
