# Generated by Django 4.2.10 on 2024-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0011_sprint_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='acceptance_tests',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='business_value',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='priority',
            field=models.CharField(choices=[('must_have', 'Must have'), ('could_have', 'Could have'), ('should_have', 'Should have'), ('wont_have_this_time', "Won't have this time")], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
