# Generated by Django 4.2.10 on 2024-03-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0012_userstory_acceptance_tests_userstory_business_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='acceptance_tests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='business_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='priority',
            field=models.CharField(blank=True, choices=[('must_have', 'Must have'), ('could_have', 'Could have'), ('should_have', 'Should have'), ('wont_have_this_time', "Won't have this time")], max_length=50),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.sprint'),
        ),
    ]
