# Generated by Django 4.2.10 on 2024-03-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0013_alter_userstory_acceptance_tests_and_more'),
        ('scrum', '0014_alter_project_name'),
    ]

    operations = [
    ]
