# Generated by Django 4.2.10 on 2024-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0015_merge_20240311_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'ordering': ['story_number']},
        ),
        migrations.AddField(
            model_name='userstory',
            name='original_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='story_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='workflow',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=50),
        ),
    ]
