# Generated by Django 4.2.10 on 2024-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0016_alter_userstory_options_userstory_original_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='business_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='original_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userstory',
            unique_together={('name', 'project')},
        ),
    ]
