# Generated by Django 4.2.10 on 2024-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0017_alter_userstory_business_value_alter_userstory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='users',
            field=models.ManyToManyField(to='scrum.user'),
        ),
    ]
