# Generated by Django 5.0.2 on 2024-03-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0019_remove_userstory_users_userstory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='duration',
            new_name='velocity',
        ),
    ]
