# Generated by Django 5.0.2 on 2024-03-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0020_rename_duration_sprint_velocity'),
        ('scrum', '0021_remove_userstory_unique_name_and_more'),
    ]

    operations = [
    ]
