# Generated by Django 5.0.2 on 2024-03-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0022_merge_20240320_1755'),
        ('scrum', '0022_merge_20240320_1802'),
    ]

    operations = [
    ]
