# Generated by Django 5.0.2 on 2024-03-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0023_merge_20240320_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
