# Generated by Django 5.0.2 on 2024-04-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0026_task_accepted_alter_task_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
