# Generated by Django 5.0.2 on 2024-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0027_task_done_task_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstory',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
