# Generated by Django 5.0.2 on 2024-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0028_userstory_accepted_userstory_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
