# Generated by Django 5.0.2 on 2024-04-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0030_task_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.AddField(
            model_name='userstory',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
