# Generated by Django 5.0.2 on 2024-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0031_remove_task_comment_userstory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
