# Generated by Django 5.0.2 on 2024-04-07 09:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0032_task_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2024, 4, 7, 9, 50, 20, 789381, tzinfo=datetime.timezone.utc))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('logged_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('description', 'user_story'), name='unique_task_user_story_description'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.task'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.user'),
        ),
    ]
