# Generated by Django 5.0.2 on 2024-04-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0033_timeentry_task_unique_task_user_story_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
