# Generated by Django 5.0.2 on 2024-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0034_alter_timeentry_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
