# Generated by Django 5.0.2 on 2024-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0035_task_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_number']},
        ),
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(default=1),
        ),
    ]
