# Generated by Django 5.0.2 on 2024-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0037_more_default_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(),
        ),
    ]
