# Generated by Django 5.0.2 on 2024-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0039_timeentry_time_to_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
