# Generated by Django 5.0.2 on 2024-04-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0040_timeentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.user'),
        ),
    ]
