# Generated by Django 5.0.2 on 2024-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0042_remove_timeentry_time_to_finish_task_time_to_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_to_finish',
            field=models.PositiveIntegerField(),
        ),
    ]
